java_library(
    name = "model",
    visibility = ["//visibility:public"],
    exports = [
        "//model/src/main/java/org/dubh/engage/json",
        "//model/src/main/java/org/dubh/engage/model",
    ],
)
