java_test(
    name = "GeneratorTest",
    srcs = ["GeneratorTest.java"],
    data = ["//src/test/java/org/dubh/engage/testdata:example.json"],
    deps = [
        "//src/main/java/org/dubh/engage",
        "//src/test/java/org/dubh/engage/util",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)
