java_library(
    name = "mojo",
    srcs = glob(["*.java"]),
    deps = [
        "@maven//:org_apache_maven_maven_plugin_api",
        "@maven//:org_apache_maven_plugin_tools_maven_plugin_annotations",
    ],
)
