java_test(
    name = "ConfigurationModelFactoryTest",
    srcs = ["ConfigurationModelFactoryTest.java"],
    deps = [
        "//src/main/java/org/dubh/engage/json",
        "//src/main/java/org/dubh/engage/model",
        "@maven//:junit_junit",
    ],
)
