java_test(
    name = "ConfigurationModelFactoryTest",
    srcs = ["ConfigurationModelFactoryTest.java"],
    data = ["//src/test/java/org/dubh/engage/testdata:example.json"],
    deps = [
        "//src/main/java/org/dubh/engage/json",
        "//src/main/java/org/dubh/engage/model",
        "//src/test/java/org/dubh/engage/util",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)
