java_test(
    name = "CommandlineFlagParserTest",
    srcs = ["CommandlineFlagParserTest.java"],
    deps = [
        "//src/main/java/org/dubh/engage/runtime",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)
