java_test(
    name = "CommandlineFlagParserTest",
    srcs = ["CommandlineFlagParserTest.java"],
    deps = [
        "//runtime/src/main/java/org/dubh/engage",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)
