java_library(
    name = "json",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//model/src/main/java/org/dubh/engage/model",
        "@maven//:org_json_json",
    ],
)
